services:
  mariadb:
    image: mariadb:latest
    container_name: maria_db
    environment:
      MARIADB_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: